FROM python:3.11-slim

WORKDIR /app

COPY firstbutton/src/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY firstbutton/src/backend/ ./src/backend/

WORKDIR /app/src/backend/demo/codes

EXPOSE 8000


CMD ["sh", "-c", "celery -A celery_app worker --concurrency=1 -l info & uvicorn main:app --host 0.0.0.0 --port 8000"]
